/* generated by UI Editor, (c)2011 Actions */
#ifndef _MAINMENU_STY_H
#define _MAINMENU_STY_H

#define  STYLE0                            0x0000
#define  MUSIC                             0x0000
#define  STY_MUSIC_PIC                     0x1000
#define  STY_MUSIC_TEXT                    0x2000
#define  STY_MUSIC_INFO                    0x2001
#define  BROWSER                           0x0001
#define  STY_BROWSER_PIC                   0x1001
#define  STY_BROWSER_TEXT                  0x2002
#define  STY_BROWSER_INFO                  0x2003
#define  RECORD                            0x0002
#define  STY_RECORD_PIC                    0x1002
#define  STY_RECORD_TEXT                   0x2004
#define  STY_RECORD_INFO                   0x2005
#define  RADIO                             0x0003
#define  STY_RADIO_PIC                     0x1003
#define  STY_RADIO_TEXT                    0x2006
#define  STY_RADIO_INFO                    0x2007
#define  SETTING                           0x0004
#define  STY_SETTING_PIC                   0x1004
#define  STY_SETTING_TEXT                  0x2008
#define  STY_SETTING_INFO                  0x2009
#define  NOWPLAY                           0x0005
#define  STY_PLAYING_PIG                   0x1005
#define  STY_NOWPLAY_TEXT                  0x200a
#define  STY_NOWPLAY_INFO                  0x200b
#define  LASTPLAY                          0x0006
#define  STY_LASTPLAY_TEXT                 0x200c
#define  USER1                             0x0007
#define  STY_USER1_PIC                     0x1006
#define  STY_USER1_TEXT                    0x200d
#define  STY_USER1_INFO                    0x200e
#define  USER2                             0x0008
#define  STY_USER2_PIC                     0x1007
#define  STY_USER2_TEXT                    0x200f
#define  STY_USER2_INFO                    0x2010

#endif //_MAINMENU_STY_H 
