/* generated by UI Editor, (c)2011 Actions */
#ifndef _MUSIC_STY_H
#define _MUSIC_STY_H

#define  STYLE0                            0x0000
#define  MUSIC_PLAY                        0x0000
#define  LOOP_MODE_PICBOX                  0x1000
#define  SHUFFLE_MODE_PICBOX               0x1001
#define  TRACK_NUMBER_BOX                  0x3000
#define  MUSIC_CURTIME_TIMERBOX            0x4000
#define  MUSIC_PLAY_PROGRESSBAR            0x5000
#define  ALBUM_ART_PICBOX                  0x1002
#define  EQ_MODE_PICBOX                    0x1003
#define  PLAY_STATUS_PICBOX                0x1004
#define  ALBUM_ART_REGION                  0x2000
#define  ID3_MUSIC_ALBUM_PICBOX            0x1005
#define  ID3_MUSIC_ARTIST_PICBOX           0x1006
#define  ID3_MUSIC_TITLE_PICBOX            0x1007
#define  ID3_TITLE_TEXTBOX                 0x2001
#define  ID3_ARTIST_TEXTBOX                0x2002
#define  ID3_ALBUM_TEXTBOX                 0x2003
#define  ID3_INFO_TEXTBOX                  0x2004
#define  ID3_MUSIC_INFO_PICBOX             0x1008
#define  SHOW_LYRIC_TEXTBOX                0x2005

#endif //_MUSIC_STY_H 
