/* generated by UI Editor, (c)2011 Actions */
#ifndef _COMMON_STY_H
#define _COMMON_STY_H

#define  STYLE_COMMON                      0x0000
#define  HEADBAR                           0x0000
#define  HEADBAR_ICON                      0x1000
#define  HEADBAR_BATTERY                   0x1001
#define  HEADBAR_CARD                      0x1002
#define  SHUTOFF                           0x0001
#define  SHUTOFF_TIME                      0x1003
#define  LOW_POWER                         0x0002
#define  FULL_CHARGE_TEXT                  0x2000
#define  LOW_POWER_TEXT                    0x2001
#define  LOW_POWER_BATTERY                 0x1004
#define  LOW_POWER_ICON                    0x1005
#define  FULL_CHARGE_ICON                  0x1006
#define  FULL_CHARGE_BATTERY               0x1007
#define  LOCK                              0x0003
#define  LOCK_HOLD                         0x1008
#define  LOCK_ANIMATION                    0x1009
#define  SCREEN                            0x0004
#define  DIGIT_CLOCK_TIME_24               0x4000
#define  DIGIT_CLOCK_TIME_12               0x4001
#define  DIGIT_CLOCK_TIME_AMPM             0x100a
#define  DIGIT_CLOCK_DATE                  0x4002
#define  DIALOG_MSG                        0x8000
#define  DIALOG_ASK                        0x8001
#define  DIALOG_USB                        0x8002
#define  USB_TIME_CLEAR                    0x100b
#define  USB_TIME_ONE                      0x100c
#define  USB_TIME_TWO                      0x100d
#define  USB_TIME_THREE                    0x100e
#define  USB_TIME_FOUR                     0x100f
#define  USB_TIME_FIVE                     0x1010
#define  DIRLIST                           0x6000
#define  FILELIST                          0x6001
#define  MENULIST                          0x6002
#define  MENULIST_HEAD                     0x6003
#define  MENULIST_TITLE                    0x6004
#define  MENULIST_OPTION                   0x6005
#define  MENULIST_OPTION_TITLE             0x6006
#define  PARAM_SIMPLE                      0x7000
#define  PARAM_TIME_24                     0x7001
#define  PARAM_TIME_12                     0x7002
#define  PARAM_DATE                        0x7003
#define  SLIDER_VOLUMEBAR                  0x0013
#define  VOLUMEBAR_LIMIT                   0x1011
#define  VOLUMEBAR_CURRENT                 0x1012
#define  VOLUMEBAR_CURRENT_CLEAR           0x1013
#define  VOLUMEBAR_SPEAKER                 0x1014
#define  VOLUMEPROGRESSBAR                 0x5000
#define  VOLUMEBAR_LEFT                    0x1015
#define  VOLUMEBAR_RIGHT                   0x1016
#define  CURRENT_VOLUME_VALUE              0x2002
#define  VOLUME_PROCESSBAR_PARAM           0x0060
#define  SLIDER_SETEQ                      0x9000
#define  DELETED                           0x0015
#define  DELETED_INFOR                     0x2003
#define  DELETED_ANIM                      0x1017
#define  PROGRESSBAR_NUM                   0x5001
#define  PROGRESSBAR_LEFT                  0x1018
#define  PROGRESSBAR_RIGHT                 0x1019
#define  CURRENT_VALUE                     0x2004
#define  TEXT_MIN                          0x2005
#define  PIC_LIGHT_ICON                    0x101a

typedef struct volume_processbar_param
{
    unsigned short processbar_length;    /* 进度条长度 */
}volume_processbar_param;

#endif //_COMMON_STY_H 
