/* generated by UI Editor, (c)2011 Actions */
#ifndef _CONFIG_STY_H
#define _CONFIG_STY_H

#define  STYLE0                            0x0000
#define  SCENE_CHARGING                    0x0000
#define  STY_CFG_CHARGING                  0x1000

#endif //_CONFIG_STY_H 
