/* generated by UI Editor, (c)2011 Actions */
#ifndef _CONFIG_RES_H
#define _CONFIG_RES_H

#define  CFG_BACKGROUND                    0x0
#define  CFG_CHARGE_0                      0x1
#define  CFG_CHARGE_1                      0x2
#define  CFG_CHARGE_2                      0x3
#define  CFG_CHARGE_3                      0x4
#define  CFG_CHARGE_4                      0x5

#endif //_CONFIG_RES_H 
