debug=0;

tab=setting;
DISP_EN=app setting;
DISP_CH=系统配置;
DISPLAY=1;

tab_layer1=ap_onff; 
tabname =setting;
DISP_EN=ap on/off select;
DISP_CH=应用开/关选择;
DISPLAY=1;

tab_layer1=common_parameters; 
tabname =setting;
DISP_EN=ap common parameters;
DISP_CH=各应用公共参数;
DISPLAY=1;

tab_layer1=hardware_config; 
tabname =setting;
DISP_EN=peripheral hardware configuration;
DISP_CH=外围硬件配置;
DISPLAY=1;

tab_layer1=test_debug; 
tabname =setting;
DISP_EN=test & debug configuration;
DISP_CH=测试调试选项;
DISPLAY=0;

tab_layer2=tts_option; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=tts option;
DISP_CH=状态语音播报选项;
DISPLAY=1;

tab_layer2=battery_charge_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=battery charge configuration;
DISP_CH=电池充电配置;
DISPLAY=0;

tab_layer2=emi_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=emi configuration;
DISP_CH=EMI相关配置;
DISPLAY=0;

tab_layer2=volume_control; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=volume control parameters;
DISP_CH=音量控制参数配置;
DISPLAY=1;

tab_layer2=key_tone_control; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=key tone control parameters;
DISP_CH=按键音控制参数配置;
DISPLAY=1;

tab_layer2=mute_control; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=mute control parameters;
DISP_CH=静音控制参数配置;
DISPLAY=0;

tab_layer2=alarm_control; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=alarm control parameters;
DISP_CH=闹钟控制参数配置;
DISPLAY=0;

tab=usb;
DISP_EN=usb property;
DISP_CH=USB属性;
DISPLAY=1;

tab_layer1=usb_sound; 
tabname =usb;
DISP_EN=usb sound configuration;
DISP_CH=USB音箱配置;
DISPLAY=1;

tab_layer1=usb_card_reader; 
tabname =usb;
DISP_EN=usb card reader configuration;
DISP_CH=USB读卡器配置;
DISPLAY=1;

tab=radio;
DISP_EN=radio property;
DISP_CH=收音机属性;
DISPLAY=0;

tab=linein;
DISP_EN=linein property;
DISP_CH=音频输入属性;
DISPLAY=0;

tab=btstack;
DISP_EN=btstack property;
DISP_CH=蓝牙协议栈属性;
DISPLAY=1;

tab_layer1=bt_address; 
tabname=btstack;
DISP_EN=bt address high three bytes;
DISP_CH=蓝牙地址高3字节配置;
DISPLAY=1;

tab=btmanager;
DISP_EN=btmanager property;
DISP_CH=蓝牙管理器属性;
DISPLAY=1;

tab=btplay;
DISP_EN=btplay property;
DISP_CH=蓝牙播歌属性;
DISPLAY=1;

tab=btcall;
DISP_EN=btcall property;
DISP_CH=蓝牙打电话属性;
DISPLAY=1;

tab_layer1=btcall_volume_control; 
tabname=btcall;
DISP_EN=btcall volume control;
DISP_CH=通话音量控制参数配置;
DISPLAY=0;

tab_layer1=btcall_ring_parameter; 
tabname=btcall;
DISP_EN=btcall ring parameter;
DISP_CH=来电铃音参数配置;
DISPLAY=0;

tab_layer1=aec_parameters; 
tabname=btcall;
DISP_EN=aec parameters configuration;
DISP_CH=AEC参数配置;
DISPLAY=0;

tab_layer2=aec_nonlinear_parameters; 
tab_layer1_name=aec_parameters; 
tabname=btcall;
DISP_EN=aec nonlinear processing parameters;
DISP_CH=AEC非线性处理参数配置;
DISPLAY=0;

tab_layer2=aec_noise_reduction_parameters; 
tab_layer1_name=aec_parameters; 
tabname=btcall;
DISP_EN=aec noise reduction parameters;
DISP_CH=AEC降噪处理参数配置;
DISPLAY=0;

tab_layer2=aec_echo_residual_parameters; 
tab_layer1_name=aec_parameters; 
tabname=btcall;
DISP_EN=aec echo residual parameters;
DISP_CH=AEC回声残留参数配置;
DISPLAY=0;

tab=record;
DISP_EN=record property;
DISP_CH=录音属性;
DISPLAY=0;

key=SETTING_APP_SUPPORT_CARDPLAY;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=ap_onff;    
tabname=setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support card playing:0-not support, 1-support;
DISP_CH=是否支持卡播放功能:0-不支持,1-支持;
DISPLAY=1;

key=SETTING_APP_SUPPORT_UHOSTPLAY;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=ap_onff;    
tabname=setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support uhost:0-not support, 1-support;
DISP_CH=是否支持U盘播放功能:0-不支持,1-支持;
DISPLAY=1;

key=SETTING_APP_SUPPORT_LINEIN;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=ap_onff;    
tabname=setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support linein:0-not support, 1-support;
DISP_CH=是否支持linein播放功能:0-不支持,1-支持;
DISPLAY=1;

key=SETTING_APP_SUPPORT_FMRADIO;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=ap_onff;    
tabname=setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support fm:0-not support, 1-support;
DISP_CH=是否支持FM收音机:0表示不支持FM，1表示支持FM;
DISPLAY=1;

key=SETTING_APP_SUPPORT_BT_INBACK;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=ap_onff;    
tabname=setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support bluetooth run in back:0-not supported,1-supported;
DISP_CH=是否支持后台蓝牙:0-不支持, 1-支持;
DISPLAY=1;

key=SETTING_APP_SUPPORT_BTPLAY;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=ap_onff;    
tabname=setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support bluetooth a2dp play:0-not supported,1-supported;
DISP_CH=是否支持蓝牙播歌:0-不支持, 1-支持;
DISPLAY=1;

key=SETTING_APP_SUPPORT_BTCALL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=ap_onff;    
tabname=setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support bluetooth hfp call:0-not supported,1-supported;
DISP_CH=是否支持蓝牙免提:0-不支持, 1-支持;
DISPLAY=1;

key=SETTING_APP_SUPPORT_USBBOX;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=ap_onff;    
tabname=setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support usb box:0-not supported,1-supported;
DISP_CH=是否支持USB音箱:0-不支持, 1-支持;
DISPLAY=1;

key=SETTING_APP_SUPPORT_USBMSC;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=ap_onff;    
tabname=setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support usb msc:0-not supported,1-supported;
DISP_CH=是否支持大容量磁盘功能:0-不支持, 1-支持;
DISPLAY=1;

key=SETTING_APP_SWITCH_SEQUENCE;
type=ARRAY;
operate=EDIT;
len=;
RANGE=;
tabname=setting;
DISP_EN=app switch sequence:0 btplay,1 card play,2 uhost play,3 linein,4 fm radio,5 usound;
DISP_CH=应用切换顺序:0蓝牙,1播卡,2播u盘,3linein,4fm,5usb音箱;默认值表示开机默认进入的应用，数值意义参见case_type.h中的宏定义 APP_FUNC_XXX;
DISPLAY=1;

key=SETTING_ONOFF_LOWPOWER_MODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-2;
step=1;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=low power mode:0 not support low power, 1 normal low power, 2 deep low power.
DISP_CH=低功耗模式:0表示不支持低功耗模式；1表示普通低功耗模式，此模式下唤醒方式较多，支持热拔插，唤醒快；2表示超低功耗模式，此模式下唤醒方式有限，有条件的支持热拔插，唤醒较慢
DISPLAY=1;

key=SETTING_ONOFF_LOWPOWER_TIMER;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-10;
step=1;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=low power time:0 for limit if idle, 1 means 1 minute.
DISP_CH=进入低功耗时间:以分钟为单位；0表示一空闲就进入低功耗模式
DISPLAY=1;

key=SETTING_ONOFF_POWEROFF_TIMER;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-120;
step=1;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=power save:0 for never, 1 means 1 minute.
DISP_CH=省电关机时间:0表示不启动省电关机，单位为1分钟；如果支持低功耗模式，那么从进入低功耗后开始计时
DISPLAY=1;

key=SETTING_ONOFF_POWEROFF_BT_WAITPAIR_TIMER;
type=DATA;
operate=SINGLE;
len=;
RANGE=1-120;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=bluetooth power save:1 means 1 minute.
DISP_CH=蓝牙省电关机时间:该配置项在“省电关机时间”不为0时有效，单位为1分钟；如果支持低功耗模式，那么该配置项就无意义了
DISPLAY=1;

key=SETTING_INPUT_SUPPORT_IR;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer1_name=hardware_config; 
tabname =setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持,1:支持; 
DISP_EN=support IR:0-not support, 1-support;
DISP_CH=是否支持红外遥控器:0表示不支持，1表示支持;
DISPLAY=0;

key=SETTING_INPUT_IR_CODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-2;
tab_layer1_name=hardware_config; 
tabname =setting;
RANGE_DISP_EN=0:0xbf00,1:0xff00,2:0x7f80;  
RANGE_DISP_CH=0:0xbf00,1:0xff00,2:0x7f80; 
DISP_EN=ir code:0-2 分别是0:0xbf00,1:0xff00,2:0x7f80;
DISP_CH=红外遥控编码类型:0xbf00,1:0xff00,2:0x7f80;
DISPLAY=0;

key=SETTING_INPUT_SUPPORT_TK;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tabname=setting;
RANGE_DISP_EN=0:no touch key,1:support touch key;  
RANGE_DISP_CH=0:不支持触摸按键,1:支持触摸按键; 
DISP_EN=support TK:0-not support, 1-support;
DISP_CH=是否支持触摸按键:0表示不支持，1表示支持;
DISPLAY=0;

key=SETTING_INPUT_TK_KEY_ARRAY;
type=ARRAY;
operate=EDIT;
len=;
RANGE=;
tabname=setting;
DISP_EN=tk key array:logic key id, for phy tk1, tk2, ...;
DISP_CH=触摸按键定义:按键逻辑ID，对应于物理TK1，TK2，。。。;
DISPLAY=0;

key=SETTING_INPUT_KEY_ARRAY;
type=ARRAY;
operate=EDIT;
len=;
RANGE=;
tab_layer1_name=hardware_config; 
tabname =setting;
DISP_EN=key array:first num is key num,27-pow,14-next_voladd,15-prev_vol-,1-play,2-prev,3-next,4-vol,5-v+,6-v-,7-mode,8-eq,9-rep,10-mute;
DISP_CH=按键定义:first num is key num,27-pow,14-next_voladd,15-prev_vol-,1-play,2-prev,3-next,4-vol,5-v+,6-v-,7-mode,8-eq,9-rep,10-mute;
DISPLAY=0;

key=SETTING_INPUT_ENABLE_DOUBLE_CLICK;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=hardware_config; 
tabname =setting;
RANGE_DISP_EN=0:disable,1:enable;  
RANGE_DISP_CH=0:禁止,1:使能; 
DISP_EN=double click option:0-disable,1-enable;
DISP_CH=双击按键开关:0表示禁止，1表示使能;
DISPLAY=0;

key=SETTING_INPUT_DOUBLE_CLICK_DELAY_TIMER;
type=DATA;
operate=SINGLE;
len=;
RANGE=100,120,140,160,180,200,220,240,260,280,300;
tab_layer1_name=hardware_config; 
tabname =setting;
DISP_EN=double click delay time:default 160ms;
DISP_CH=双击按键延迟时间:单位为ms；该值表示按键按下->按键抬起->按键按下->按键抬起这3个动作间隔的时间;
DISPLAY=0;

key=SETTING_AUDIO_OUTPUT_CHANNAL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-4;
tab_layer1_name=hardware_config; 
tabname =setting;
RANGE_DISP_EN=0:DAC,1:I2S,2:SPDIF,3:DAC+I2S,4:DAC+SPDIF;  
RANGE_DISP_CH=0:DAC,1:I2S,2:SPDIF,3:DAC+I2S,4:DAC+SPDIF; 
DISP_EN=audio out channl:0 DAC ，1 I2S，2 SPDIF，3 DAC+I2S，4 DAC+SPDIF;
DISP_CH=音频输出通道:0 DAC ，1 I2S，2 SPDIF，3 DAC+I2S，4 DAC+SPDIF;
DISPLAY=0;

key=SETTING_AUDIO_INNER_PA_SET_MODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1,2,3;
tab_layer1_name=hardware_config; 
tabname =setting;
RANGE_DISP_EN=0:single end + non direct drive,1:single end + direct drive,2:difference + non direct drive,3:difference + direct drive ;  
RANGE_DISP_CH=0:单端+非直驱,1:单端+直驱,2:差分+非直驱,3:差分+直驱; 
DISP_EN=set PA mode:0,single end + non direct drive,1,single end + direct drive,2,difference + non direct drive,3,difference + direct drive
DISP_CH=设置PA输出模式:0,单端+非直驱,1,单端+直驱,2,差分+非直驱,3,差分+直驱
DISPLAY=0;

key=SETTING_AUDIO_INPUT_CHANNAL;
type=DATA;
operate=SINGLE;
len=;
RANGE=2-4;
tab_layer1_name=hardware_config; 
tabname =setting;
RANGE_DISP_EN=2:difference mic,3: single end mic, 4: digital mic;  
RANGE_DISP_CH=2:单端mic,3:差分mic,4:数字mic;
DISP_EN=audio in channl;
DISP_CH=音频输入通道:2=单端mic，3=差分mic，4=数字mic;
DISPLAY=0;

key=SETTING_SOUND_ENABLE_KEYTONE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=key_tone_control;
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:disable,1:enable;  
RANGE_DISP_CH=0:关闭,1:开启;
DISP_EN=keytone:0-disable,1-enable;
DISP_CH=按键音开关:0-关闭,1-开启;
DISPLAY=1;

key=SETTING_SOUND_ENABLE_KEYTONE_OVERLAY;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=key_tone_control;
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:disable,1:enable;  
RANGE_DISP_CH=0:声音不叠加按键音,1:声音叠加按键音;
DISP_EN=keytone overlay:0-disable,1-enable;
DISP_CH=按键音叠加开关:0表示有声音输出时不输出按键音，1表示即使有声音输出也要把按键音叠加上去;
DISPLAY=0;

key=SETTING_SOUND_ENABLE_TTS;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=tts_option;
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:disable,1:enable;  
RANGE_DISP_CH=0:关闭,1:开启;
DISP_EN=tts option:0-disable,1-enable;
DISP_CH=状态语音播报选项:0-关闭,1-开启;
DISPLAY=1;

key=SETTING_SOUND_TTS_LANGUAGE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer2_name=tts_option;
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:chinese,1:english;  
RANGE_DISP_CH=0:中文,1:英文;
DISP_EN=tts language:0 for chinese, 1 for english;
DISP_CH=TTS播报语音类型:0表示中文，1表示英文;
DISPLAY=0;

key=SETTING_SOUND_UNMUTE_BY_APP_SWITCH;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=mute_control;
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:do not unmute,1:unmute;  
RANGE_DISP_CH=0:不解除静音,1:解除静音;
DISP_EN=support unmute by app switch:0-do not unmute,1-unmute;
DISP_CH=是否切换应用解除静音:0-不解除,1-解除;
DISPLAY=0;

key=SETTING_SOUND_UNMUTE_BY_INPUT;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=mute_control;
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:do not unmute,1:unmute;  
RANGE_DISP_CH=0:不解除静音,1:解除静音;
DISP_EN=support unmute by input:0-do not unmute,1-unmute;
DISP_CH=是否任意按键解除静音:0-不解除,1-解除;
DISPLAY=0;

key=SETTING_SOUND_VOLUME_GRADE;
type=DATA;
operate=SINGLE;
len=;
RANGE=1-31;
tab_layer2_name=volume_control;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=volume grade number:1~31;
DISP_CH=声音等级数:1~31;
DISPLAY=0;

key=SETTING_SOUND_DEFAULT_MAIN_VOLUME;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-31;
tab_layer2_name=volume_control;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=default main volume:0~31;
DISP_CH=默认主音量:升级后首次开机默认主音量，或者也可以作为每次开机的重置主音量;
DISPLAY=1;

key=SETTING_SOUND_DEFAULT_CALL_VOLUME;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-31;
tab_layer2_name=volume_control;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=default call volume:0~31;
DISP_CH=默认打电话音量:升级后首次开机默认打电话音量，或者也可以作为每次开机的重置打电话音量;
DISPLAY=0;

key=SETTING_SOUND_MIN_VOLUME_POWERON;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-31;
step=1;
tab_layer2_name=volume_control;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=power on mix volume:0~31;
DISP_CH=开机最小音量:避免开机听不到任何声音;
DISPLAY=0;

key=SETTING_SOUND_MAX_VOLUME_POWERON;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-31;
tab_layer2_name=volume_control;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=power on max volume:0~31;
DISP_CH=开机最大音量:避免开机声音太大;
DISPLAY=0;

key=SETTING_SOUND_KT_TTS_MIN_VOLUME;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-31;
tab_layer2_name=volume_control;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=keytone and tts min volume:0~31,0-keytone and tts mute when volume is 0
DISP_CH=按键音和TTS最小声音:0~31,0表示在音量为0时没有按键音和TTS
DISPLAY=0;

key=SETTING_SOUND_MAIN_VOLUME_GAIN;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-9;
tab_layer2_name=volume_control;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=main volume gain:0 ~ 9, for 0db ~ -9db
DISP_CH=主音量负增益（衰减）:0 ~ 9 表示 0db ~ -9db
DISPLAY=0;

key=SETTING_SOUND_CALL_VOLUME_GAIN;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-9;
tab_layer2_name=volume_control;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=call volume gain:0 ~ 9, for 0db ~ -9db
DISP_CH=打电话音量负增益（衰减）:0 ~ 9 表示 0db ~ -9db
DISPLAY=0;

key=SETTING_DISPLAY_SUPPORT_LED_SEGMENT;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer1_name=hardware_config; 
tabname =setting;
RANGE_DISP_EN=0:Dont support LED,1:support LED;  
RANGE_DISP_CH=0:不支持LED,1:支持LED;
DISP_EN=support LED segment:0-not support, 1-support;
DISP_CH=是否支持LED数码管显示:0 不支持 1支持;
DISPLAY=0;

key=SETTING_DISPLAY_LED_SEGMENT_LIGHT_TIMER;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-120;
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=backlight time:1 means 1s;
DISP_CH=背光时间:单位1秒，0表示不休眠;
DISPLAY=0;

key=SETTING_BAT_CHARGE_MODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=battery_charge_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:inner charge, 1:outer charge;  
RANGE_DISP_CH=0:内部充电, 1:外部充电;
DISP_EN= bat charge mode;
DISP_CH= 电池充电方式:0=内部充电, 1=外部充电;
DISPLAY=0;

key=SETTING_BAT_CHARGE_CURRENT;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1,2,3,4,5,6,7;
tab_layer2_name=battery_charge_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:25mA, 1:50mA, 2:100mA, 3:150mA, 4:200mA, 5:300mA, 6:400mA, 7:500mA;  
RANGE_DISP_CH=0:25mA, 1:50mA, 2:100mA, 3:150mA, 4:200mA, 5:300mA, 6:400mA, 7:500mA;
DISP_EN= set bat charge current;
DISP_CH= 电池充电电流值:0=25mA, 1=50mA, 2=100mA, 3=150mA, 4=200mA, 5=300mA, 6=400mA, 7=500mA;
DISPLAY=0;

key=SETTING_BAT_CHARGE_VOLTAGE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1,2,3,4,5,6,7;
tab_layer2_name=battery_charge_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:4.2V, 1:4.23V, 2:4.26V, 3:4.29, 4:4.32V, 5:4.35V, 6:4.38V, 7:4.41V;  
RANGE_DISP_CH=0:4.2V, 1:4.23V, 2:4.26V, 3:4.29, 4:4.32V, 5:4.35V, 6:4.38V, 7:4.41V;
DISP_EN= set bat charge voltage;
DISP_CH= 电池充电恒压值:0=4.2V, 1=4.23V, 2=4.26V, 3=4.29, 4=4.32V, 5=4.35V, 6=4.38V, 7=4.41V;
DISPLAY=0;

key=SETTING_BAT_CHARGE_FULL_TTS;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer2_name=battery_charge_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:not support,1:support;  
RANGE_DISP_CH=0:不支持每分钟播报一次TTS,1:支持每分钟播报一次TTS;
DISP_EN=charge full tts enable:0-not support, 1-support;
DISP_CH=充电已满TTS使能:0 不支持 1支持 每分钟播报一次TTS;
DISPLAY=0;

key=SETTING_TIMEALARM_SNOOZE_TIMER;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-30;
tab_layer2_name=alarm_control; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=snooze timer:0 ~ 30 minutes, 0 - don't support snooze;
DISP_CH=贪睡时间:单位为分钟，0表示不支持贪睡;
DISPLAY=0;

key=SETTING_TIMEALARM_SNOOZE_MAX_TIMES;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-30;
tab_layer2_name=alarm_control; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=snooze times:0 ~ 10 times, 0 - snooze unlimited;
DISP_CH=贪睡最多次数:0表示无限次贪睡;
DISPLAY=0;

key=SETTING_TIMEALARM_ALARM_OVERTIME;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-30;
tab_layer2_name=alarm_control; 
tab_layer1_name=common_parameters; 
tabname =setting;
DISP_EN=alarm overtime:0 ~ 30 minutes, 0 - alarm forever;
DISP_CH=闹钟超时时间:单位为分钟，0表示会一直闹直到用户关闭;
DISPLAY=0;

key=SETTING_CARD_CMD_PAD_LEVEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1,2,3,4,5,6,7;
tab_layer2_name=emi_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:level 0,1:level 1,2:level 2,3:level 3,4:level 4,5:level 5,6:level 6,7:level 7;
RANGE_DISP_CH=0:0级,1:1级,2:2级,3:3级,4:4级,5:5级,6:6级,7:7级;
DISP_EN= card cmd pin pad level:0 ~ 7 level,0 is lowest;
DISP_CH= 卡cmd pin驱动能力配置:0 ~ 7级，0为最低级;
DISPLAY=0;

key=SETTING_CARD_CLK_PAD_LEVEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1,2,3,4,5,6,7;
tab_layer2_name=emi_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:level 0,1:level 1,2:level 2,3:level 3,4:level 4,5:level 5,6:level 6,7:level 7;
RANGE_DISP_CH=0:0级,1:1级,2:2级,3:3级,4:4级,5:5级,6:6级,7:7级;
DISP_EN= card clk  pinpad level;
DISP_CH= 卡clk pin驱动能力配置:0 ~ 7级，0为最低级;
DISPLAY=0;

key=SETTING_CARD_DAT_PAD_LEVEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1,2,3,4,5,6,7;
tab_layer2_name=emi_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:level 0,1:level 1,2:level 2,3:level 3,4:level 4,5:level 5,6:level 6,7:level 7;
RANGE_DISP_CH=0:0级,1:1级,2:2级,3:3级,4:4级,5:5级,6:6级,7:7级;
DISP_EN= card data pin pad level;
DISP_CH= 卡data pin驱动能力配置:0 ~ 7级，0为最低级;
DISPLAY=0;

key=SETTING_CARD_INT_CLK;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=emi_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:10MHZ ,1:20MHZ;
RANGE_DISP_CH=0:10MHZ ,1:20MHZ;
DISP_EN= card init clock;
DISP_CH= 卡初始频率: 0=10MHz ,1=20MHz;
DISPLAY=0;

key=SETTING_CARD_RW_CLK;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1,2;
tab_layer2_name=emi_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=0:10MHZ,1:20MHZ,2:mcu pll;
RANGE_DISP_CH=0:10MHZ,1:20MHZ,2:mcu pll;
DISP_EN= card read&write clock;
DISP_CH= 卡读写速度:0为固定10M，1为固定20M，2为mcu的pll时钟;
DISPLAY=0;

key=SETTING_CARD_MAX_CLK;
type=DATA;
operate=SINGLE;
len=;
RANGE=20,25,30,35,40,45,50;
tab_layer2_name=emi_config; 
tab_layer1_name=common_parameters; 
tabname =setting;
RANGE_DISP_EN=20:20MHZ,25:25MHZ,30:30MHZ,35:35MHZ,40:40MHZ,45:45MHZ,50:50MHZ;
RANGE_DISP_CH=20:20MHZ,25:25MHZ,30:30MHZ,35:35MHZ,40:40MHZ,45:45MHZ,50:50MHZ;
DISP_EN= card max read write clock for MCUPLL type;
DISP_CH= 卡最大读写时钟:卡读写速度选择为MCUPLL时此项才有效，可选[20,25,30,35,40,45,50]MHz;
DISPLAY=0;

key=SETTING_UHOST_USE_DELAY;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer1_name=uhost_config; 
tabname =setting;
RANGE_DISP_EN=0:no support uhost delay,1:support uhost delay;
RANGE_DISP_CH=0:不支持uhost延时,1:支持uhost延时;
DISP_EN=hardware support uhost delay:0-not support, 1-support;
DISP_CH=是否支持uhost延时:0 不支持 1支持;
DISPLAY=1;

key=SETTING_HARDWARE_SUPPORT_CARD;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer1_name=hardware_config; 
tabname =setting;
RANGE_DISP_EN=0:no support card,1:support card;
RANGE_DISP_CH=0:不支持卡,1:支持卡;
DISP_EN=hardware support card:0-not support, 1-support;
DISP_CH=硬件是否支持卡:0 不支持 1支持;
DISPLAY=1;

key=SETTING_HARDWARE_SUPPORT_UHOST;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer1_name=hardware_config; 
tabname =setting;
RANGE_DISP_EN=0:no support uhost,1:support uhost;
RANGE_DISP_CH=0:不支持UHOST,1:支持UHOST;
DISP_EN=hardware support uhost:0-not support, 1-support;
DISP_CH=硬件是否支持UHOST:0 不支持 1支持;
DISPLAY=1;

key=SETTING_STUB_TEST_DEBUG_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer1_name=test_debug; 
tabname =setting;
RANGE_DISP_EN=0:no support stub,1:support stub;
RANGE_DISP_CH=0:不支持STUB测试调试,1:支持STUB测试调试;
DISP_EN=stub test&debug support:0-not support, 1-support;
DISP_CH=是否支持STUB测试调试:0 不支持 1支持;
DISPLAY=1;

key=SETTING_STUB_PRINT_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer1_name=test_debug; 
tabname =setting;
RANGE_DISP_EN=0:no support stub print,1:support stub print;
RANGE_DISP_CH=0:不支持STUB 打印,1:支持STUB 打印;
DISP_EN=stub print support:0-not support, 1-support;
DISP_CH=是否支持STUB 打印:0 不支持 1支持;
DISPLAY=1;

key=SETTING_UART_PRINT_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tab_layer1_name=test_debug; 
tabname =setting;
RANGE_DISP_EN=0:no support uart print,1:support uart print;
RANGE_DISP_CH=0:不支持UART 打印,1:支持UART 打印;
DISP_EN=stub uart print support:0-not support, 1-support;
DISP_CH=是否支持UART 打印:0 不支持 1支持;
DISPLAY=1;


key=RADIO_AP_ID_BAND;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1,2;
tabname =radio;
RANGE_DISP_EN=0:chinese band,1:japanese band,2:europe band;
RANGE_DISP_CH=0:中国频段,1:日本频段,2:欧洲频段;
DISP_EN=default band:0-normal，1-japan，2-europe;
DISP_CH=电台默认波段:0-中国频段，1-日本频段，2-欧洲频段;
DISPLAY=0;

key=RADIO_AP_ID_SEEKMODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname =radio;
RANGE_DISP_EN=0:hardware mode,1:software mode;
RANGE_DISP_CH=0:硬件搜索模式,1:软件搜索模式;
DISP_EN=seek mode:0-hardware mode, 1-software mode;
DISP_CH=默认搜台模式:0-硬件seek模式，1-软件seek模式;
DISPLAY=0;


key=RADIO_AP_ID_HINT_MODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname =radio;
RANGE_DISP_EN=0:keytone hint mode,1:led trinkle mode;
RANGE_DISP_CH=0:按键音提示,1:闪灯提示;
DISP_EN=seek mode:0-hardware mode, 1-software mode;
DISP_CH=默认搜台提示模式:0-按键音提示模式，1-灯闪烁提示模式;
DISPLAY=0;

key=RADIO_ROUT_SEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=radio;
RANGE_DISP_EN=0:fm in rout,1:line in rout;
RANGE_DISP_CH=0:fm通道,1:line in通道;
DISP_EN=rout in mode:0-fm in, 1-linein in;
DISP_CH=fm in通道:0表示fm in，1表示linein in;
DISPLAY=0;

key=FMENGINE_AP_ID_SEEKTH;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-127;
tabname=radio;
DISP_EN=threshold for auto search
DISP_CH=搜台门限
DISPLAY=0;

key=FMENGINE_CHANNEL_SEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=radio;
RANGE_DISP_EN=0:analog channel,1:digital channel;
RANGE_DISP_CH=0:模拟通道,1:数字通道;
DISP_EN=select radio sourse 0:analog channel;1 digital channel;
DISP_CH=radio通道选择:0-模拟通道;1-数字通道;
DISPLAY=0;

key=FMENGINE_GAIN_INPUT;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-7;
tabname=radio;
RANGE_DISP_EN=0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
RANGE_DISP_CH=0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISP_EN=FM gain:0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISP_CH=FM增益:0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISPLAY=1;

key=FMENGINE_GAIN_ADC;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tabname=radio;
DISP_EN=FM adc gain:0-15, for 0-45db, step 3db
DISP_CH=FM ADC 增益:0-15 对应 0-45db, 每级递增3db
DISPLAY=1;

key=FMENGINE_FREQ_32K_13M;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=radio;
DISP_EN=FM input clk:0=32678, 1=13M
DISP_CH=FM 输入频率:0是外接晶振32768Hz,1是cpu输出13M
DISPLAY=1;

key=FMENGINE_CLK_PAD_LEVEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-7;
tabname=radio;
DISP_EN=clk gpio pad level
DISP_CH=clk gpio驱动能力
DISPLAY=1;

key=USOUND_TYPE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=usb;
RANGE_DISP_EN=0:sound card mode,1:speaker mode;
RANGE_DISP_CH=0:usb声卡模式,1:usb音箱模式;
DISP_EN=select usound type 0--sound card;1--speaker;
DISP_CH=usb输出类型选择:0-usb声卡;1-usb音箱;
DISPLAY=0;

key=USB_VID;
type=STR;
operate=EDIT;
len=6;
RANGE=;
tabname=usb;
DISP_EN=USB VID;
DISP_CH=USB VID:设备厂商ID;
DISPLAY=1;

key=USB_SOUND_PID;
type=STR;
operate=EDIT;
len=6;
RANGE=;
tab_layer1_name=usb_sound; 
tabname =usb;
DISP_EN=USB SOUND PID;
DISP_CH=USB SOUND PID:同一VID下不同usb设备ID不能相同;
DISPLAY=1;

key=USB_CARDREADER_PID;
type=STR;
operate=EDIT;
len=6;
RANGE=;
tab_layer1_name=usb_card_reader; 
tabname =usb;
DISP_EN=USB CARDREADER PID;
DISP_CH=USB CARDREADER PID:同一VID下不同usb设备ID不能相同;
DISPLAY=1;

key=INF_USB_VENDOR;
type=STR;
operate=EDIT;
len=8;
RANGE=;
tabname=usb;
DISP_EN=usb vendor;
DISP_CH=USB设备厂商(<8字符);
DISPLAY=1;

key=INF_SOUND_PRODUCT_NAME;
type=STR;
operate=EDIT;
len=16;
RANGE=;
tab_layer1_name=usb_sound; 
tabname =usb;
DISP_EN=usb sound product name;
DISP_CH=USB SOUND名称:播放加录音功能USB设备名;
DISPLAY=1;

key=INF_CARDREADER_PRODUCT_NAME;
type=STR;
operate=EDIT;
len=16;
RANGE=;
tab_layer1_name=usb_card_reader; 
tabname =usb;
DISP_EN=USB cardreader product name;
DISP_CH=USB CARDREADER名称:高速读卡器设备名;
DISPLAY=1;

key=INF_INQUIRY_INFORMATION_FOB;
type=STR;
operate=EDIT;
len=58;
RANGE=;
tab_layer1_name=usb_card_reader; 
tabname =usb;
DISP_EN=infomation of Udisk;
DISP_CH=Udisk 信息;
DISPLAY=1;

key=INF_UDISK_LABEL;
type=STR;
operate=EDIT;
len=11;
RANGE=;
tab_layer1_name=usb_card_reader; 
tabname =usb;
DISP_EN=show udisk label;
DISP_CH=磁盘卷标名;
DISPLAY=1;

key=BTSTACK_DEVICE_NAME;
type=STR;
operate=EDIT;
len=29;
RANGE=;
tabname=btstack;
DISP_EN=bluetooth device name:max 29 bytes;
DISP_CH=蓝牙设备名称:最大29字符;
DISPLAY=1;

key=BTSTACK_BLE_DEVICE_NAME;
type=STR;
operate=EDIT;
len=29;
RANGE=;
tabname=btstack;
DISP_EN=bluetooth ble_device name:max 29 bytes
DISP_CH=BLE蓝牙设备名称:最大29字符
DISPLAY=1;

key=BTSTACK_BLE_ADV_MANUFACTUREER_ID;
type=DATA;
operate=EDIT;
len=4;
RANGE=0-9999;
tabname=btstack;
DISP_EN=ble_device's manufactureer ID
DISP_CH= BLE广播设备制造商标识符
DISPLAY=0;

key=BTSTACK_FIX_PIN_CODE;
type=STR;
operate=EDIT;
len=15;
RANGE=;
tabname=btstack;
DISP_EN=bluetooth fix pin code:max 15 bytes;
DISP_CH=蓝牙配对密码:最大15字符;
DISPLAY=0;

key=BTSTACK_CLASS_OF_DEVICE;
type=DATA;
operate=EDIT;
len=;
RANGE=0-16777215;
tabname=btstack;
DISP_EN=class of device: detail information on www.bluetooth.org/zh-cn/specification/assigned-numbers/baseband;
DISP_CH=蓝牙设备类型:高字节表示major service，中字节表示major device，低字节表示minor device，各比特意义参考 www.bluetooth.org/zh-cn/specification/assigned-numbers/baseband;
DISPLAY=0;

key=BTSTACK_BDADD_HIGH3BYTES;
type=DATA;
operate=EDIT;
len=;
RANGE=0-16777215;
tab_layer1_name=bt_address;
tabname=btstack;
DISP_EN=bt addr[byte5, byte4, byte3];
DISP_CH=蓝牙地址高3字节;
DISPLAY=1;

key=BTSTACK_OUTPUT_POWER_VALUE;
type=DATA;
operate=SINGLE;
len=;
RANGE=9-12;
tabname=btstack;
DISP_EN=Output Power,9:-2dbm,10:1dbm, 11:4dbm, 12:7dbm
DISP_CH=发射功率,9:-2dbm,10:1dbm, 11:4dbm, 12:7dbm
DISPLAY=0;

key=BTSTACK_CAPACITANCE_VALUE_ARRAY;
type=ARRAY;
operate=EDIT;
len=;
RANGE=;
tabname=btstack;
DISP_EN=;
DISP_CH=相对常温电容补偿值表(扩大10倍)，-20:0.6;0:0.9;20:0.3;40:-0.5;60:-0.9;75:-0.8;
DISPLAY=1;

key=BTMANAGER_ENABLE_A2DP_CP;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1,2;
tabname=btmanager;
RANGE_DISP_EN=0:not support a2dp,1:DTCP,2:SCMS-T;
RANGE_DISP_CH=0:不支持A2DP,1:支持DTCP,2:支持SCMS-T;
DISP_EN=CP:0-not support,1-DTCP,2-SCMS-T;
DISP_CH=CP:0-不支持,1-支持DTCP,2-支持SCMS-T;
DISPLAY=0;

key=BTMANAGER_ENABLE_AVDTP_AAC;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btmanager;
RANGE_DISP_EN=0:not support AAC,1:support AAC;
RANGE_DISP_CH=0:不支持AAC格式,1:支持AAC格式;
DISP_EN=support aac:0-disable,1-enable;
DISP_CH=支持AAC格式:0-关闭,1-开启;
DISPLAY=1;

key=BTMANAGER_ENABLE_AVRCP_VOLUME_SYNC;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tabname=btmanager;
RANGE_DISP_EN=0:not support volume SYNC,1:support SYNC;
RANGE_DISP_CH=0:不支持音量同步,1:支持音量同步;
DISP_EN=enable avrcp1.4 absolute volume control:0 - disable,1 - enable;
DISP_CH=是否使能AVRCP1.4音量同步功能:0-关闭,1-开启;
DISPLAY=1;

key=BTMANAGER_ENABLE_HFP_VOLUME_SYNC;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tabname=btmanager;
RANGE_DISP_EN=0:not support HFP volume SYNC,1:support HFP volume SYNC;
RANGE_DISP_CH=0:不支持通话音量同步,1:支持通话音量同步;
DISP_EN=enable hfp absolute volume control:0 - disable,1 - enable;
DISP_CH=是否使能HFP音量同步功能:0-关闭,1-开启;
DISPLAY=1;

key=BTMANAGER_ENABLE_HFP_BAT_REPORT;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tabname=btmanager;
RANGE_DISP_EN=0:not support battery report,1:support battery report;
RANGE_DISP_CH=0:不支持小机电量上报,1:支持小机电量上报;
DISP_EN=battery report enable: 0 - disable,1 - enable;
DISP_CH=是否使能电池电量更新:0-关闭,1-开启;
DISPLAY=1;

key=BTMANAGER_ENABLE_HFP_PHONEBOOK;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tabname=btmanager;
RANGE_DISP_EN=0:no support phonebook,1:support phonebook;
RANGE_DISP_CH=0:不支持电话本,1:支持电话本;
DISP_EN=phone book enable:0 - disable, 1 - enable;
DISP_CH=电话本功能:0，关闭，1，打开;
DISPLAY=0;

key=BTMANAGER_ENABLE_SPP;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btmanager;
RANGE_DISP_EN=0:no spp,1:support spp;
RANGE_DISP_CH=0:不支持spp,1:支持spp;
DISP_EN=support spp:0-disable,1-enable;
DISP_CH=支持spp服务:是否支持手机APK控制蓝牙音箱功能，0-不支持,1-支持;
DISPLAY=0;

key=BTMANAGER_ENABLE_BLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btmanager;
RANGE_DISP_EN=0:no ble,1:support ble;
RANGE_DISP_CH=0:不支持ble,1:支持ble;
DISP_EN=support ble:0-disable,1-enable;
DISP_CH=支持ble功能:是否支持ble功能，0-不支持,1-支持;
DISPLAY=0;

key=BTMANAGER_ENABLE_AUTO_CONNECT;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btmanager;
RANGE_DISP_EN=0:not support auto connect,1:support auto connect;
RANGE_DISP_CH=0:不支持自动回连,1:支持自动回连;
DISP_EN=enable auto connection:0-disable,1-enable;
DISP_CH=自动回连开启:0-关闭,1-开启;
DISPLAY=0;

key=BTMANAGER_RECONNECT_ANOTHER_TIMES;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-20;
tabname=btmanager;
DISP_EN=bt engine auto connect another profile count:0 for all;
DISP_CH=后台回连另外一个服务的次数限制:0表示无限制;
DISPLAY=0;

key=BTMANAGER_AUTO_CONNECT_COUNT_TIMEOUT;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tabname=btmanager;
DISP_EN=auto connect count:0-always;
DISP_CH=超时断开后自动回连次数:0表示一直回连，1~20表示有限次;
DISPLAY=0;

key=BTMANAGER_AUTO_CONNECT_COUNT_STARTUP;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tabname=btmanager;
DISP_EN=bt engine auto connect count for startup reconnect:0 for all;
DISP_CH=开机回连次数:0表示无限制，1~15表示有限次;
DISPLAY=0;

key=BTMANAGER_AUTO_CONNECT_COUNT_MODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tabname=btmanager;
DISP_EN=bt engine auto connect count for mode switch reconnect:0 for all;
DISP_CH=切MODE键进入蓝牙回连次数:0表示无限制，1~15表示有限次;
DISPLAY=0;

key=BTMANAGER_AUTO_CONNECT_INTERVAL;
type=DATA;
operate=SINGLE;
len=;
RANGE=1-60;
tabname=btmanager;
DISP_EN=bt engine auto connect timer:uint 1s;
DISP_CH=自动回连时间间隔:单位1s;
DISPLAY=0;

key=BTMANAGER_MAX_PAIRED_LIST_MEMBER;
type=DATA;
operate=SINGLE;
len=;
RANGE=1-8;
tabname=btmanager;
DISP_EN=local device max paired list size:1-8;
DISP_CH=本地配对列表的最大成员个数:目前支持最多保存8个设备信息;
DISPLAY=1;

key=BTMANAGER_SUPPORT_DEVICE_NUM;
type=DATA;
operate=SINGLE;
len=;
RANGE=1-2;
tabname=btmanager;
DISP_EN=support divice num:1-2;
DISP_CH=支持同时连接几台设备:1-2;
DISPLAY=0;

key=BTMANAGER_VERIFICATION_APK_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btmanager;
RANGE_DISP_EN=1:verification apk,2:don't verification apk;
RANGE_DISP_CH=1:验证APK,2:不验证APK;
DISP_EN=verification apk:1-verification apk,2-don't verification apk;
DISP_CH=验证:1-验证APK，2-不验证APK，以向后兼容旧版本APK;
DISPLAY=0;

key=BTPLAY_FRONT_AUTOPLAY_CNT;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-10;
tabname=btplay;
DISP_EN=auto play try after link:0-do not auto play;
DISP_CH=连接成功后自动发播放命令的次数:0表示不发送;
DISPLAY=0;

key=BTPLAY_FRONT_AVRCP_TTS_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btplay;
RANGE_DISP_EN=0:not support avrcp TTS,1:support avrcp TTS;
RANGE_DISP_CH=0:不支持avrcp语音播报,1:支持avrcp语音播报;
DISP_EN=support avrcp tts play:0-no,1-yes;
DISP_CH=支持AVRCP状态播报:0-不支持,1-支持;
DISPLAY=1;

key=BTPLAY_AAC_PLAY_DELAY_START;
type=DATA;
operate=SINGLE;
len=;
RANGE=69,92,115,138,161;
tabname=btplay;
DISP_EN=aac play start delay:69ms to 161ms, space 23ms
DISP_CH=aac播放起始延时:单位为ms，间隔为23ms，即解码单元时长
DISPLAY=0;

key=BTPLAY_AAC_PLAY_DELAY_LOWEST;
type=DATA;
operate=SINGLE;
len=;
RANGE=46,69,92,115,138,161;
tabname=btplay;
DISP_EN=aac play lowest delay:46ms to 161ms, space 23ms
DISP_CH=aac播放最低延时:单位为ms，间隔为23ms，即解码单元时长
DISPLAY=0;

key=BTPLAY_SBC_PLAY_DELAY_START;
type=DATA;
operate=SINGLE;
len=;
RANGE=69,92,115,138,161,184,207;
tabname=btplay;
DISP_EN=sbc play start delay:69ms to 207ms, space 23ms
DISP_CH=sbc播放起始延时:单位为ms，间隔为23ms，即解码单元时长
DISPLAY=0;

key=BTPLAY_SBC_PLAY_DELAY_LOWEST;
type=DATA;
operate=SINGLE;
len=;
RANGE=46,69,92,115,138,161,184,207;
tabname=btplay;
DISP_EN=sbc play lowest delay:46ms to 207ms, space 23ms
DISP_CH=sbc播放最低延时:单位为ms，间隔为23ms，即解码单元时长
DISPLAY=0;

key=BTCALL_FRONT_CHF_CAG_EXCH_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btcall;
RANGE_DISP_EN=0:not support CAG/CHF switch,1:support CAG/CHF switch;
RANGE_DISP_CH=0:不支持CAG/CHF切换,1:支持CAG/CHF切换;
DISP_EN=support chf & cag exchage:0-disable,1-enable;
DISP_CH=支持切换音箱和手机通话:0-不支持,1-支持,按NEXT/PREV键进行切换;
DISPLAY=1;

key=BTCALL_MICIN_OP_GAIN;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-7;
tabname=btcall;
DISP_EN=mic-in gain:0-26db,1-30db,2-31.5db,3-33db,4-34.5db,5-36db,6-37.5db,7-39db
DISP_CH=蓝牙mic增益:0-26db,1-30db,2-31.5db,3-33db,4-34.5db,5-36db,6-37.5db,7-39db
DISPLAY=0;

key=BTCALL_MICIN_ADC_GAIN;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tabname=btcall;
DISP_EN=call adc gain:0-15, for 0-45db, step 3db
DISP_CH=打电话 ADC 增益:0-15 对应 0-45db, 每级递增3db
DISPLAY=0;

key=BTCALL_SPEAKER_CHANNEL_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=1-3;
tab_layer1_name=btcall_volume_control;
tabname=btcall;
RANGE_DISP_EN=1:using right channel,2:using left channel,3:using dual channel;
RANGE_DISP_CH=1:右声道输出,2:左声道输出,3:双声道输出;
DISP_EN=speaker channel enable:1-right channel,2-left channel,3-both channel;
DISP_CH=打电话时喇叭声道使能:1：右声道，2：左声道，3：双声道；（双声道可能会导致回声消除效果变差）;
DISPLAY=0;

key=BTCALL_SPEAKER_CHANNEL_WEAK_SEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-2;
tab_layer1_name=btcall_volume_control;
tabname=btcall;
RANGE_DISP_EN=0:no reduction,1:right reduction,2:left reduction;
RANGE_DISP_CH=0:无衰减,1:右声道衰减,2:左声道衰减;
DISP_EN=speaker channel weak selection:0-no weak, 1-right channel, 2-left channel;
DISP_CH=打电话时喇叭声道衰减选择:0-不衰减，1-右声道衰减，2-左声道衰减;
DISPLAY=0;

key=BTCALL_SPEAKER_CHANNEL_WEAK_VAL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-50;
tab_layer1_name=btcall_volume_control;
tabname=btcall;
DISP_EN=speaker channel weak value:0db ~ -18db;
DISP_CH=打电话时喇叭声道衰减幅度:0db ~ -18db;
DISPLAY=0;

key=BTCALL_IGNORE_UNCALLSCO;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-1;
tabname=btcall;
RANGE_DISP_EN=0:dont ignore uncall sco data,1:ignore uncall sco data;
RANGE_DISP_CH=0:不过滤非通话sco数据,1:过滤非通话sco数据;
DISP_EN=ignore the uncall sco data: 0, not ignore, 1,ignore;
DISP_CH=过滤非通话状态下的SCO数据:0：不过滤，1：过滤;
DISPLAY=0;

key=BTCALL_CALLIN_RING_MODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-2;
tab_layer1_name=btcall_ring_parameter;
tabname=btcall;
RANGE_DISP_EN=0:only ring,1:only phonebook,2:ring + phonebook;
RANGE_DISP_CH=0:仅铃声,1:仅电话本播报,2:铃声+电话本播报;
DISP_EN=enable callring :0-only ring,1-only phonebook,2-ring + phonebook
DISP_CH=来电铃声模式:0-仅铃声,1-仅电话本播报,2-铃声+电话本播报
DISPLAY=1;

key=BTCALL_CALLIN_RING_SPACE_TIME;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-30;
tab_layer1_name=btcall_ring_parameter;
tabname=btcall;
DISP_EN=call in ring space time:unit is 1s;
DISP_CH=来电铃声间隔时长:以1s为单位，播完来电铃声后等待该时长后再循环播放;
DISPLAY=1;

key=BTCALL_CALLIN_RING_BUILDIN_SPACE_TIME;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-50;
tab_layer1_name=btcall_ring_parameter;
tabname=btcall;
DISP_EN=call in buildin ring space time:unit is 100ms;
DISP_CH=内置来电铃声间隔时长:以100ms为单位，播完内置来电铃声后等待该时长后再循环播放;
DISPLAY=1;

key=BTCALL_AEC_MODULE_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer1_name=aec_parameters;
tabname=btcall;
RANGE_DISP_EN=0:disable AEC,1:enable AEC;
RANGE_DISP_CH=0:关闭AEC模块,1:使能AEC模块;
DISP_EN=aec module enable:0-disable,1-enable;
DISP_CH=回声消除模块开关:1：打开，0：关闭;
DISPLAY=0;

key=BTCALL_AEC_NLP_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=aec_nonlinear_parameters;
tab_layer1_name=aec_parameters;
tabname=btcall;
RANGE_DISP_EN=0:disable AEC,1:enable AEC;
RANGE_DISP_CH=0:关闭AEC模块,1:使能AEC模块;
DISP_EN=aec nlp enable:0-disable,1-enable;
DISP_CH=非线性处理子模块开关:1：打开，0：关闭;
DISPLAY=0;

key=BTCALL_AEC_NLP_AGGRESSIVENESS;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tab_layer2_name=aec_nonlinear_parameters;
tab_layer1_name=aec_parameters;
tabname=btcall;
DISP_EN=aec nlp aggressiveness:0~15;
DISP_CH=非线性处理程度:整数0~15,越大代表非线性处理越厉害;
DISPLAY=0;

key=BTCALL_AEC_DT_THRESHOLD;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tab_layer2_name=aec_nonlinear_parameters;
tab_layer1_name=aec_parameters;
tabname=btcall;
DISP_EN=aec dt threshold:0~15;
DISP_CH=双讲近端语音保留程度:整数0~15，越大表示双讲是近端语音保留越多，但是可能会带来单讲的回声，需找个折中值;
DISPLAY=0;

key=BTCALL_AEC_AES_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=aec_echo_residual_parameters;
tab_layer1_name=aec_parameters;
tabname=btcall;
RANGE_DISP_EN=0:disable aec aes modular,1:enable aec aes modular;
RANGE_DISP_CH=0:关闭残留回声抑制子模块,1:打开残留回声抑制子模块;
DISP_EN=aec aes enable:0-disable,1-enable;
DISP_CH=残留回声抑制子模块开关:1：打开，0：关闭;
DISPLAY=0;

key=BTCALL_AEC_ECHO_SUPPRESS;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-40;
tab_layer2_name=aec_echo_residual_parameters;
tab_layer1_name=aec_parameters;
tabname=btcall;
DISP_EN=aec echo suppress:0~40db;
DISP_CH=回声抑制子模块单讲回声抑制比:单位dB， 0~40;
DISPLAY=0;

key=BTCALL_AEC_ECHO_SUPPRESS_ACTIVE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-40;
tab_layer2_name=aec_echo_residual_parameters;
tab_layer1_name=aec_parameters;
tabname=btcall;
DISP_EN=aec echo suppress active:0~40db;
DISP_CH=回声抑制子模块双讲回声抑制比:单位dB， 0~40;
DISPLAY=0;

key=BTCALL_AEC_ANS_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tab_layer2_name=aec_noise_reduction_parameters;
tab_layer1_name=aec_parameters;
tabname=btcall;
RANGE_DISP_EN=0:disable aec anti noise,1:enable aec anti noise;
RANGE_DISP_CH=0:关闭降噪子模块,1:打开降噪子模块;
DISP_EN=aec ans enable:0-disable,1-enable;
DISP_CH=降噪开关:1：打开，0：关闭;
DISPLAY=0;

key=BTCALL_AEC_NOISE_SUPPRESS;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-25;
tab_layer2_name=aec_noise_reduction_parameters;
tab_layer1_name=aec_parameters;
tabname=btcall;
DISP_EN=aec noise suppress:0~25db;
DISP_CH=噪声抑制比:单位dB，0~25;
DISPLAY=0;

key=BTCALL_AEC_CNG_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btcall;
RANGE_DISP_EN=0:disable comfort noise,1:enable comfort noise;
RANGE_DISP_CH=0:关闭舒适噪声子模块,1:打开舒适噪声子模块;
DISP_EN=aec cng enable:0-disable,1-enable;
DISP_CH=舒适噪声开关:1：打开，0：关闭;
DISPLAY=0;

key=BTCALL_AEC_NOISE_FLOOR;
type=DATA;
operate=SINGLE;
len=;
RANGE=-60--30;
tabname=btcall;
DISP_EN=aec noise floor value:-60db ~ -30db;
DISP_CH=舒适噪声水平:单位 dB Fs, 该值对应为负值，一般应小于-40 dB;
DISPLAY=0;

key=BTCALL_AEC_TAIL_LENGTH;
type=DATA;
operate=SINGLE;
len=;
RANGE=32,64,96,128;
tabname=btcall;
DISP_EN=aec tail length:32ms ~ 128ms;
DISP_CH=回声消除尾长:单位 ms, 32ms ~ 128ms;
DISPLAY=0;

key=BTCALL_AEC_HALF_FULL_MODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btcall;
DISP_EN=call by :<0>half or <1>full mode;
DISP_CH=通话单双工选择:选择 0单工，1全双工;
DISPLAY=0;


key=BTCALL_AGC_PRETREAT_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btcall;
RANGE_DISP_EN=0:agc pretreat disable,1:agc pretreat enable;
RANGE_DISP_CH=0:关闭前置AGC子模块,1:打开前置AGC子模块;
DISP_EN=agc pretreat enable:0-disable,1-enable;
DISP_CH=预处理AGC使能:预处理自动增益控制使能，用于放大对方的声音，1：打开，0：关闭;
DISPLAY=0;

key=BTCALL_AGC_PRETREAT_LEVEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=-30--15;
tabname=btcall;
DISP_EN=agc pretreat level:-30db ~ -15db;
DISP_CH=预处理AGC目标值:预处理自动增益控制目标值，默认设置为-22db;
DISPLAY=0;

key=BTCALL_AGC_POSTREAT_ENABLE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=btcall;
RANGE_DISP_EN=0:agc postreat disable,1:agc postreat enable;
RANGE_DISP_CH=0:关闭后置AGC子模块,1:打开后置AGC子模块;
DISP_EN=aec postreat enable:0-disable,1-enable;
DISP_CH=后端AGC使能:后端自动增益控制使能，用于放大自己的声音，1：打开，0：关闭;
DISPLAY=0;

key=BTCALL_AGC_POSTREAT_LEVEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=-30--15;
tabname=btcall;
DISP_EN=agc postreat level:-30db ~ -15db;
DISP_CH=后端AGC目标值:后端自动增益控制目标值，默认设置为-22db;
DISPLAY=0;

key=RECORD_FORMAT_TYPE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=record;
RANGE_DISP_EN=0:wav format,1:mp3 format;
RANGE_DISP_CH=0:录音为wav格式,1:录音为mp3格式;
DISP_EN=record file format:0-wav;1-mp3;
DISP_CH=录音格式:0-wav, 1-mp3;
DISPLAY=0;

key=RECORD_WAV_ENCODE_TYPE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=record;
RANGE_DISP_EN=0:wav encoding as pcm format,1:wav encoding as adpcm format;
RANGE_DISP_CH=0:wav文件为PCM编码,1:wav文件为ADPCM编码;
DISP_EN=wav code format:0-pcm,1-adpcm;
DISP_CH=wav编码格式:0-pcm, 1-adpcm;
DISPLAY=0;

key=RECORD_WAV_BITRATE;
type=DATA;
operate=SINGLE;
len=;
RANGE=5-10;
tabname=record;
RANGE_DISP_EN=5:256kbps,6:512kbps,7:768kbps,8:1024kbps,9:1411,10:1536;
RANGE_DISP_CH=5:256kbps,6:512kbps,7:768kbps,8:1024kbps,9:1411,10:1536;
DISP_EN=wav bitrate 5:256kbps, 6:512kbps, 7:768kbps,8:1024kbps,9:1411,10:1536;
DISP_CH=wav比特率:5:256kbps, 6:512kbps, 7:768kbps,8:1024kbps,9:1411,10:1536;

key=RECORD_MP3_BITRATE;
type=DATA;
operate=SINGLE;
len=;
RANGE=1-4;
tabname=record;
RANGE_DISP_EN=1:32kbps,1:64kbps,2:128kbps,3:192kbps;
RANGE_DISP_CH=1:32kbps,1:64kbps,2:128kbps,3:192kbps;
DISP_EN=mp3 bitrate 1:32kbps, 2:64kbps,3:128kbps, 4:192kbps;
DISP_CH=mp3比特率:1:32kbps, 2:64kbps,3:128kbps,4:192kbps;
DISPLAY=0;

key=RECORD_TRACK_MODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=record;
RANGE_DISP_EN=0:disable auto track,1:enable auto track;
RANGE_DISP_CH=0:关闭自动分曲,1:开启自动分曲;
DISP_EN=auto track detect switch:0-off;1-on;
DISP_CH=自动分曲模式:0-关闭,1-开启;
DISPLAY=0;

key=RECORD_AVR_MODE;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=record;
RANGE_DISP_EN=0:disable avr mode,1:enable avr mode;
RANGE_DISP_CH=0:关闭声控模式,1:开启声控模式;
DISP_EN=avr mode switch:0-off,1-on;
DISP_CH=avr模式:0-关闭,1-开启;
DISPLAY=0;

key=RECORD_GAIN_INPUT_LINEIN;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-7;
tabname=record;
RANGE_DISP_EN=0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
RANGE_DISP_CH=0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISP_EN=linein gain:0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISP_CH=录音line-in增益:0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISPLAY=0;

key=RECORD_GAIN_ADC_LINEIN;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tabname=record;
DISP_EN=linein input adc gain:0-15, for 0-45db, step 3db
DISP_CH=line-in ADC 增益:0-15 对应 0-45db, 每级递增3db
DISPLAY=0;

key=RECORD_GAIN_INPUT_MIC;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-7;
tabname=record;
DISP_EN=record mic-in gain:0-26db,1-30db,2-31.5db,3-33db,4-34.5db,5-36db,6-37.5db,7-39db
DISP_CH=录音mic增益:0-26db,1-30db,2-31.5db,3-33db,4-34.5db,5-36db,6-37.5db,7-39db
DISPLAY=0;

key=RECORD_GAIN_ADC_MIC;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tabname=record;
DISP_EN=mic input adc gain:0-15, for 0-45db, step 3db
DISP_CH=mic ADC 增益:0-15 对应 0-45db, 每级递增3db
DISPLAY=0;

key=RECORD_GAIN_INPUT_FM;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-7;
tabname=record;
RANGE_DISP_EN=0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
RANGE_DISP_CH=0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISP_EN=FM gain:0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISP_CH=录音FM增益:0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISPLAY=0;

key=RECORD_GAIN_ADC_FM;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tabname=record;
DISP_EN=FM input adc gain:0-15, for 0-45db, step 3db
DISP_CH=FM ADC 增益:0-15 对应 0-45db, 每级递增3db
DISPLAY=0;

key=RECORD_TRACK_LEVEL_BREAKSONG;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-128;
tabname=record;
DISP_EN=track detect voltage level:0-noise average;other value every step sub 0.5db;
DISP_CH=自动分曲电压门槛值:0表示采用初始录音的噪声平均值，非零则-0.5dB一级;
DISPLAY=0;

key=RECORD_TRACK_LEVEL_AVR;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-128;
tabname=record;
DISP_EN=arv voltage level:0-noise average;other value every step sub 0.5db;
DISP_CH=avr电压门槛值:0表示采用初始录音的噪声平均值，非零则-0.5dB一级;
DISPLAY=0;

key=RECORD_TRACK_DELAY;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-10;
tabname=record;
DISP_EN=avr delay time:unit second;
DISP_CH=avr延时时间:单位：s;
DISPLAY=0;

key=LINEIN_CHANNEL_SEL;
type=DATA;
operate=SINGLE;
len=;
RANGE=0,1;
tabname=linein;
DISP_EN=select linein sourse 0:analog channel;1 digital channel;
DISP_CH=linein模/数通道选择:0-模拟通道;1-数字通道;
DISPLAY=0;

key=LINEIN_GAIN_INPUT;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-7;
tabname=linein;
RANGE_DISP_EN=0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
RANGE_DISP_CH=0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISP_EN=linein gain:0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISP_CH=line-in增益:0:-12db,1:-3db,2:0db,3:1.5db,4:3db,5:4.5db,6:6db,7:7.5db;
DISPLAY=1;

key=LINEIN_GAIN_ADC;
type=DATA;
operate=SINGLE;
len=;
RANGE=0-15;
tabname=linein;
DISP_EN=linein input adc gain:0-15, for 0-45db, step 3db
DISP_CH=line-in ADC 增益:0-15 对应 0-45db, 每级递增3db
DISPLAY=1;
