/* generated by UI Editor, (c)2011 Actions */
#ifndef _LOGO_RES_H
#define _LOGO_RES_H

#define  POWER_ON_1                        0x0
#define  POWER_ON_2                        0x1
#define  POWER_ON_3                        0x2
#define  POWER_ON_4                        0x3
#define  POWER_ON_5                        0x4
#define  POWER_ON_6                        0x5
#define  POWER_ON_7                        0x6
#define  POWER_ON_8                        0x7
#define  POWER_ON_9                        0x8

#endif //_LOGO_RES_H 
