/* generated by UI Editor, (c)2011 Actions */
#ifndef _UPGRADE_RES_H
#define _UPGRADE_RES_H

#define  P_UPGRADE_POINT_1A                0x0
#define  P_UPGRADE_POINT_1INA              0x1
#define  P_UPGRADE_POINT_2A                0x2
#define  P_UPGRADE_POINT_2INA              0x3
#define  P_UPGRADE_POINT_3A                0x4
#define  P_UPGRADE_POINT_3INA              0x5
#define  P_UPGRADE_POINT_4A                0x6
#define  P_UPGRADE_POINT_4INA              0x7
#define  P_UPGRADE_POINT_5A                0x8
#define  P_UPGRADE_POINT_5INA              0x9
#define  P_UPGRADE_PROG_0                  0xa
#define  P_UPGRADE_PROG_1                  0xb
#define  UPGRADE_PROGRESS_BG               0xc
#define  S_UPGRADE_FAILED                  0x0
#define  S_UPGRADE_SUCCEED                 0x1
#define  S_UPGRADE_TIPS                    0x2
#define  S_UPGRADING                       0x3

#endif //_UPGRADE_RES_H 
