/* generated by UI Editor, (c)2011 Actions */
#ifndef _END_STY_H
#define _END_STY_H

#define  STYLE0                            0x0000
#define  END                               0x0000
#define  STY_END                           0x1000

#endif //_END_STY_H 
