/* generated by UI Editor, (c)2011 Actions */
#ifndef _END_RES_H
#define _END_RES_H

#define  POWER_OFF_0                       0x0
#define  POWER_OFF_1                       0x1
#define  POWER_OFF_2                       0x2
#define  POWER_OFF_3                       0x3
#define  POWER_OFF_4                       0x4
#define  POWER_OFF_5                       0x5
#define  POWER_OFF_6                       0x6
#define  POWER_OFF_7                       0x7
#define  POWER_OFF_8                       0x8

#endif //_END_RES_H 
